### PR TITLE
Implementation of new questionnaire (STOMP or SMP).

### PR DESCRIPTION
**Pull request by NicolasRuth**
I additionally edited the comments of the standalone.R file and therefore the man etc. - I just added the two new tests to the list.

### CODE REVIEW

**Comment by fmhoeger** [comment]
Musstest du die Datei `data/benchmarks.rda` ändern? Wenn nicht, die aus dem `master` branch nehmen (z.B. von GitHub herunterladen und die von dir geänderte überschreiben).

**Review by fmhoeger — CHANGES_REQUESTED** [review]
Is there any specific reason why you've changed the files `data/benchmarks.rda` and `data/scoring_maps.rda`? If not, take those from the master branch (e.g. download them from GitHub and overwrite the changed ones) with the result that they do no longer appear in the set of changed files.

**Review by fmhoeger — CHANGES_REQUESTED** [review]
Remove the five added RDS files from the PR. They let the tests for TPI fail.

**Review by fmhoeger — CHANGES_REQUESTED** [review]
Great, except that you now added `data/.DS_Store`. Sorry, but it should not be in the psyquest package. Add it to .gitignore to prevent commiting it in the future.

**Review by NicolasRuth — COMMENTED** [review]
ok, not sure how to it though. Will have to look into it. 
Will you merge it anyway or are you waiting for me to resolve this?

**Review by fmhoeger — APPROVED** [review]

**Pull request merged**
